MMCB/MMCB/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from products import views

urlpatterns = [
    url(r'^$', views.store_list, name='store'),
    url(r'^cart/', include('shopping.urls', namespace='cart')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^member/', include('members.urls', namespace='member')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls', namespace='posts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 以下適用於網頁讀取"settings.py"中的 MEDIA_URL 與 MEDIA_ROOT 所用
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MMCB/products/urls.py
from django.conf.urls import url
from products import views


urlpatterns = []

MMCB/products/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _


class Product(models.Model):
    name = models.CharField(_('商品名稱'), max_length=16)
    notes = models.TextField(_('商品描述'), blank=True, default='')
    onshelf_time = models.DateTimeField(_('上架時間'), default=timezone.now)
    image = models.ImageField(_('商品陳列圖片'), upload_to='ProductImages', null=True, blank=True)
    is_display = models.BooleanField(_('是否陳列商品'), default=True)
    freight_only = models.BooleanField(_('限制只能貨運'), default=False)

    def thumbnail(self):
        return mark_safe('<img src="/media/%s" width="30" height="30" />' % (self.image))
    thumbnail.short_description = 'Thumbnail'

    class Meta:
        verbose_name = '商品'
        verbose_name_plural = '所有商品'
        ordering = ['-onshelf_time', '-id']

    def __str__(self):
        return self.name
    __repr__ = __str__


class Images(models.Model):
    def get_image_filename(instance, filename):
        title = instance.product.name
        slug = slugify(title, allow_unicode=True)
        return "ProductImages/%s - %s" % (slug, filename)

    product = models.ForeignKey('Product', verbose_name=_('商品'))
    image = models.ImageField(upload_to=get_image_filename,
                              verbose_name=_('商品內容圖片'),
                              blank=True, null=True, )

    class Meta:
        verbose_name = '商品內容圖片'
        verbose_name_plural = '所有商品內容圖片'


class Item(models.Model):
    product = models.ForeignKey('Product', verbose_name=_('商品'))
    style = models.CharField(_('商品款式'), max_length=8)
    size = models.CharField(_('商品尺寸'), max_length=8)
    price = models.PositiveSmallIntegerField(_('商品價格'), default=0)
    pre_order = models.SmallIntegerField(_('預購量'), default=0)
    selling = models.PositiveSmallIntegerField(_('已出貨量'), default=0)
    selling_volume = models.PositiveSmallIntegerField(_('總出貨量'), default=0)
    reset_time = models.DateTimeField(_('上次歸零時間'), blank=True, null=True)
    is_reset = models.BooleanField(_('是否歸零'), default=False)
    is_shortage = models.BooleanField(_('是否缺貨'), default=False)

    class Meta:
        verbose_name = '商品項目'
        verbose_name_plural = '所有商品項目'

    def __str__(self):
        return "{} - {}".format(self.style, self.size)
    __repr__ = __str__

MMCB/base/views.py
from django.shortcuts import render

# Create your views here.

MMCB/products/views.py
from django.shortcuts import render
from products.models import Product


def store_list(request):
    all_products = Product.objects.all()
    context = {
        'title': 'StoreList',
        'All_Products': all_products
    }
    return render(request, 'products/store_list.html', context)

MMCB/products/templates/products/base.html
{% extends 'base.html' %}
{% block content %}
<img src="{{MEDIA_URL}}/MMCBpic.jpg" class="img-responsive center-block" alt="Responsive image" width="100%">
<div style="background-color:	#FFFFFF" class="jumbotron">
  <div class="page-helper"><h2 style="color:#E26673"> MaMaCrazyBuy: </h2></div>
  <div class="description">
    <h4>　　我們自己是非常愛買東西的媽媽！這裡秉持便宜也要有好貨，便宜也要有質感的精神～替大家挑好貨。</h4>
  </div>
</div>
{% endblock content %}

MMCB/products/templates/products/store_list.html
{% extends 'products/base.html' %}
{% block title %} MMCB商品列表 | {{ block.super }}{% endblock title %}

{% block content %} {{ block.super }}
<div class="ui special cards">
  <div class="ui four stackable cards">
    {% for good in All_Products %} {% if good.is_display %}
    <div class="ui card" id="No{{ good.id }}Card">
      <div class="blurring dimmable image">
        <div class="ui inverted dimmer">
          <div class="content">
            <div class="center">
              <div class="ui inverted pink button" data-toggle="modal" data-target="#CardModal{{ good.id }}">Add Cart</div>
            </div>
          </div>
        </div>
        <img src="{{MEDIA_URL}}/{{ good.image }}">
      </div>
      <div class="content">
        <a class="header">{{ good.name }}
          {% if good.freight_only %}<span class="right floated "><i class="shipping icon"></i></span>{% endif %}
        </a>
        <div class="meta">
          <span class="date">於 {{ good.onshelf_time }} 上架</span>
        </div>
        <div class="description">{{ good.notes |linebreaks |truncatechars:100 }}</div>
      </div>
      <div class="extra content">
        <div class="ui large transparent left icon">
          <div class="ui list">
          {% for citem in cart.items %} {% for item in good.item_set.all %} {% if item == citem.product %}
            {% if forloop.first %} <span><i class="heart outline icon"></i>你已加入購物車的有：</span> {% endif %}
            <div class="item">
              <div class="right floated content">{{ citem.product }} / {{ citem.quantity }}件</div>
            </div>
          {% endif %} {% endfor %} {% endfor %}
          </div>
        </div>
      </div>
      <div class="ui bottom attached basic pink button" data-toggle="modal" data-target="#CardModal{{good.id}}"><i class="cart icon"></i> Add Cart </div>
    </div>
    {% endif %} {% endfor %}
  </div>
</div>
{% endblock content %}

{% block footer %}
<form class="form-horizontal" role="form" method="post">
  {% for good in All_Products %} {% if good.is_display %}
  <div class="modal fade" id="CardModal{{good.id}}" role="dialog">
    <div class="modal-dialog ">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">{{good.name}}</h4>
        </div>
        <div class="modal-body"> {{ good.notes | linebreaks }}
          <div class="row">
            <div class="col-md-3"><img src="{{MEDIA_URL}}/{{ good.image }}" class="img-responsive"></div>
            <div class="col-md-9">
              <table class="table">
                <thead>
                  <tr>
                    <th class="col-md-9">款式</th>
                    <th class="col-md-3">數量</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      <!-- How to get value of text input field by JavaScript: http://stackoverflow.com/questions/11563638/javascript-how-to-get-value-of-text-input-field -->
                      <div class="form-group">
                        <select class="form-control" id="No{{good.id}}selItem">
                          {% for item in good.item_set.all %}
                            {% if item.is_shortage %}
                            <option value="{{item.id}}" data-stock={{item.pre_order}} disabled>{{ item }} </option>
                            {% else %}
                            <option value="{{item.id}}" data-stock={{item.pre_order}}>{{ item }}</option>
                            {% endif %}
                          {% empty %}
                          <option value=-1>尚無款式</option>
                          {% endfor %}
                        </select>
                      </div>
                    </td>
                    <td>
                      <div class="form-group">
                        <select class="form-control" id="No{{good.id}}selQty">
                          {% for num in "123456789" %}
                          <option value="{{num}}">{{num}}</option>
                          {% endfor %}
                        </select>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="ui button" data-dismiss="modal">取消</button>
          {% if good.item_set.all %}<button type="button" class="positive ui button" onclick="addCart({{good.id}})"><i class="icon cart"></i> 加入購物車</button>{% endif %}
          <hr>
          <style>
            .bottom-buffer {
              margin-bottom: 30px;
            }
          </style>
          {% for goodImg in good.images_set.all %}
          <div class="ui segment">
            <img src="{{MEDIA_URL}}/{{ goodImg.image }}" class="ui fluid rounded image" alt="商品圖片">
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% endif %} {% endfor %}
</form>
{% endblock footer %}

{% block js-foot %} {{ block.super }}
<script type="text/javascript">
  $('.special.cards .image').dimmer({
    on: 'hover'
  });

  function addCart(goodID) {
    var selItemId = $("#No" + goodID + "selItem").val();
    var selItemQty = $("#No" + goodID + "selQty").val();
    window.location = "/cart/add/?id=" + selItemId + "&quantity=" + selItemQty;
  }
</script>
{% endblock js-foot %}