MMCB/MMCB/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from products import views

urlpatterns = [
    url(r'^$', views.store_list, name='store'),
    url(r'^cart/', include('shopping.urls', namespace='cart')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^member/', include('members.urls', namespace='member')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls', namespace='posts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 以下適用於網頁讀取"settings.py"中的 MEDIA_URL 與 MEDIA_ROOT 所用
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MMCB/checkout/urls.py
from django.conf.urls import url
from checkout import views

urlpatterns = [
    url(r'^$', views.checkout_page, name='page'),
    url(r'^orderinfo/$', views.checkout_orderinfo, name='orderinfo')
]

MMCB/members/urls.py
from django.conf.urls import url
from members import views

urlpatterns = [
    url(r'^$', views.member_page, name='page'),
    url(r'^info/$', views.member_info, name='info'),
    url(r'^shoppinglist/$', views.member_shoppinglist, name='shoppinglist'),
    url(r'^shoppinglist/(?P<number>\d+)/$', views.member_order, name='order'),
    url(r'^orderstatus/(?P<number>\d+)/(?P<do>.+)/(?P<dt>.+)/(?P<account>\d+)/$', views.member_orderstatus, name='orderstatus'),
    url(r'^others/$', views.member_others, name='others'),
]

MMCB/shopping/urls.py
from django.conf.urls import url
from shopping import views

urlpatterns = [
    url(r'^$', views.show, name='shopping-cart-show'),
    url(r'^add/$', views.add, name='shopping-cart-add'),
    url(r'^remove/$', views.remove, name='shopping-cart-remove'),
    url(r'^clear/$', views.clear, name='shopping-cart-remove'),
]

MMCB/checkout/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _
from members.models import PersonalInfo
from products.models import Item
# 訂單編號、買家、連絡賣家、查看訂單
# 結帳時間
# 商品名稱/商品編號 (多個)
# 數量/商品總價
# 運費
# 結帳總金額
# 交易狀況（待付款，請轉帳至.../賣家確認金額中/已付款）
# 可執行動作 （通知已付款、(放棄此訂單/待賣家確認放棄/已放棄)）

# 訂單資訊:
# 賣出時間、商品名稱/編號、數量/商品總價、運費、總金額、付款方式/交易狀況、可執行動作（通知出貨）
# 會員帳號(ID)、姓名、手機、信箱、剩餘儲值金

# 買家交易明細:
# 付款資訊: 匯款銀行名、匯款銀行代碼、轉出帳號末五碼、匯款人姓名、匯款時間
# 收件人資料：收件人姓名、手機、收件地址

# 給賣家的話:

# 賣家出貨資訊:
# 出貨資料：出貨進度、預計出貨方式、預計出貨時間
# 給買家的話


class PurchaseOrder(models.Model):
    STATUS = {
        'Unpaid': 'UPD',
        'Paid': 'PAD',
        'ComfirmPayment': 'CFP',
        'Shipping': 'SPN',
        'Shipped': 'SPD',
        'Abandon': 'ABN',
        'CancelAbandonment': 'CCA',
        'ComfirmAbandonment': 'CFA',
        'Abandoned': 'ABD',
    }
    ORDER_STATUS = (
        (STATUS['Unpaid'], '待付款/匯款'),
        (STATUS['Paid'], '通知已付款'),
        (STATUS['ComfirmPayment'], '確認已付款'),
        (STATUS['Shipping'], '商品準備中'),
        (STATUS['Shipped'], '商品已寄出'),
        (STATUS['Abandon'], '放棄此訂單'),
        (STATUS['CancelAbandonment'], '取消放棄此訂單'),
        (STATUS['ComfirmAbandonment'], '待賣家確認放棄'),
        (STATUS['Abandoned'], '已放棄'),
    )
    METHOD = {
        'Family': 'FML',
        'KerryTJ': 'KTJ',
    }
    SHIP_METHOD = (
        (METHOD['Family'], '全家'),
        (METHOD['KerryTJ'], '大榮貨運'),
    )

    number = models.DecimalField(_('訂單編號'), max_digits=16, decimal_places=0,
                                 validators=[MinValueValidator(0)])
    buyer = models.ForeignKey(PersonalInfo, verbose_name=_('買家'))
    order_time = models.DateTimeField(_('訂購時間'), default=timezone.now)
    sold_goods = models.ManyToManyField(Item, verbose_name=_('已買商品'))
    freight = models.PositiveSmallIntegerField(_('運費'))
    ship_method = models.CharField(_('運送方式'), max_length=3, choices=SHIP_METHOD, default=METHOD['KerryTJ'])
    address = models.CharField(_('寄送地址'), max_length=64, default='')
    total = models.PositiveIntegerField(_('總額'))
    buyer_notes = models.TextField(_('備註'), default='')
    status = models.CharField(_('訂單狀態'), max_length=3, choices=ORDER_STATUS, default=STATUS['Unpaid'])
    order_notes = models.TextField(_('訂單清單'), default='')
    remittance_account = models.CharField(_('匯款帳號'), max_length=6, default="")
    remittance_time = models.DateTimeField(_('匯款日期時間'), blank=True, null=True)
    shipment_number = models.CharField(_('包裹貨件編號'), max_length=13, default="")
    shipment_time = models.DateTimeField(_('寄出日期時間'), blank=True, null=True)
    renounce_time = models.DateTimeField(_('放棄日期時間'), blank=True, null=True)

    class Meta:
        verbose_name = '購物清單'
        verbose_name_plural = '所有購物清單'
        ordering = ['-order_time']

    def get_sold_goods(self):
        return "\n".join([str(good) for good in self.sold_goods.all()])

MMCB/members/models.py
from django.db import models
from django.core import validators
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _
import allauth.app_settings


class PersonalInfo(models.Model):
    GENDER = (
        ('M', '男性'),
        ('F', '女性'),
    )
    user = models.OneToOneField(allauth.app_settings.USER_MODEL)
    name = models.CharField(_('姓名'), max_length=16)
    gender = models.CharField(_('性別'), max_length=1, choices=GENDER, default=GENDER[1][0])
    birthday = models.DateField(_('生日'), help_text=_('範例：1993/11/29'))
    phone = models.CharField(
        _('手機'), max_length=10, help_text=_('範例：0912456999'),
        validators=[validators.RegexValidator(
            r'^09\d{8}$', _('請輸入正確的手機號碼'), 'invalid')])
    email = models.EmailField()
    money = models.PositiveIntegerField(_('已消費金額'), default=0)

    class Meta:
        verbose_name = '會員資料'
        verbose_name_plural = '所有會員資料'
        ordering = ['-id']

    def __str__(self):
        return self.name


class Addresses(models.Model):
    personalinfo = models.ForeignKey('PersonalInfo', verbose_name=_('會員'))
    address = models.CharField(
        _('地址'), max_length=64, blank=True, default='',
    )

    class Meta:
        verbose_name = '地址'
        verbose_name_plural = '所有地址'

    def __str__(self):
        return self.address
    __repr__ = __str__


# alphanumeric = RegexValidator(r'^\d{5,6}$', '只能輸入5~6位數字') #Only alphanumeric characters are allowed.
class Accounts(models.Model):
    personalinfo = models.ForeignKey('PersonalInfo', verbose_name=_('會員'))
    account = models.CharField(
        _('匯款帳號(5碼)/無摺局號(6碼)'), max_length=6,
        blank=True, default='', validators=[RegexValidator(r'^\d{5,6}$', '請輸入5位帳號或6位局號！')],
    )

    class Meta:
        verbose_name = '匯款帳號/無摺局號'
        verbose_name_plural = '所有匯款帳號/無摺局號'

    def __str__(self):
        return self.account
    __repr__ = __str__


class FamilyNumber(models.Model):
    personalinfo = models.ForeignKey('PersonalInfo', verbose_name=_('會員'))
    number = models.CharField(
        _('全家店鋪號'), max_length=6,
        blank=True, default='', validators=[RegexValidator(r'^\d{6}$', '請輸入6位全家店鋪號！')],
    )

    class Meta:
        verbose_name = '全家店鋪號'
        verbose_name_plural = '所有全家店鋪號'

    def __str__(self):
        return self.number
    __repr__ = __str__

MMCB/base/views.py
from django.shortcuts import render

# Create your views here.

MMCB/checkout/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from functools import reduce
from datetime import datetime
from carton.cart import Cart
from checkout.models import PurchaseOrder
from members.models import PersonalInfo
from products.models import Item


def checkout_page(request):
    errors = []
    cart = Cart(request.session)
    freight_only = any([item.product.product.freight_only for item in cart.items])
    cost_total = cart.total
    if cart.is_empty:
        return redirect(reverse('store'))
    else:
        if request.POST:
            cart_list = [v for k, v in cart.cart_serializable.items()]
            cal_price = reduce(lambda x, y: x + y, [i['quantity'] * int(i['price']) for i in cart_list])
            delivery = request.POST.get('delivery')
            try:
                shopper = PersonalInfo.objects.get(id=request.user.personalinfo.id)
                if cart.total == cal_price and delivery is not None:
                    order = PurchaseOrder.objects.create(
                        number=0,
                        buyer=shopper,
                        order_time=datetime.now(),
                        freight=0 if cart.total > 1500 else
                        60 if delivery.isdigit() else 90,
                        ship_method='FML' if delivery.isdigit() else 'KTJ',
                        address=delivery,
                        total=cart.total,
                        buyer_notes=request.POST.get('shopper_notes'),
                        order_notes=cart_list
                    )
                    order.number = float(datetime.now().strftime('%y%m%d%H%M%S')) + float(order.id)
                    order.total = order.total + order.freight

                    # 更改為預購模式！
                    for d in cart_list:
                        item = get_object_or_404(Item, id=d['product_pk'])
                        order.sold_goods.add(item)
                        item.pre_order += d['quantity']
                        # print ('id={} / 存貨={} / 售貨={} / 總售貨={}'.format(
                        #     item.id, item.stock,
                        #     item.sold, item.total_sold
                        # ))
                        item.save()
                    order.save()
                    cart.clear()
                    return HttpResponseRedirect(reverse('checkout:orderinfo'))
                else:
                    errors.append('資料有誤 或 尚未填寫，請重新整理再次一次')
            except Exception as e:
                print ('%s (%s)' % (e, type(e)))
    context = {
        'title': '結帳清單',
        'errors': errors,
        'cost_total': cost_total,
        'freight_only': freight_only,
    }
    return render(request, 'checkout/checkout-page.html', context)


def checkout_orderinfo(request):
    errors = []
    newest_order = None
    user_orderlist = request.user.personalinfo.purchaseorder_set.all()
    try:
        newest_orderid = user_orderlist.order_by('-order_time')[0].id
        newest_order = get_object_or_404(PurchaseOrder, id=newest_orderid)
    except:
        errors.append('無法取得訂單資料')
    context = {
        'title': '訂單資訊',
        'myorder': newest_order,
        'errors': errors,
    }
    return render(request, 'checkout/checkout-orderinfo.html', context)

MMCB/checkout/templates/checkout/base.html
{% extends 'base.html' %}

{% block content %}{{ block.super }}
<div class="ui three steps">
  <div class="disabled step" id="cart_step">
    <i class="shop icon"></i>
    <div class="content">
      <div class="title">購物車</div>
      <div class="description">MyCart</div>
    </div>
  </div>
  <div class="disabled step" id="ordercomfirm_step">
    <i class="payment icon"></i>
    <div class="content">
      <div class="title">訂單確認</div>
      <div class="description">Confirm Order</div>
    </div>
  </div>
  <div class="disabled step" id="orderinfo_step">
    <i class="info icon"></i>
    <div class="content">
      <div class="title">訂單資訊</div>
      <div class="description">MyOrder</div>
    </div>
  </div>
</div>
{% if errors %}
<div class="ui error message">
  <i class="close icon"></i>
  <div class="header">錯誤警告</div>
  <ul class="list">
    {% for error in errors %}
    <li>{{ error }}</li>
    {% endfor %}
  </ul>
</div>
{% endif %}
{% endblock content %}

MMCB/checkout/templates/checkout/checkout-orderinfo.html
{% extends 'checkout/base.html' %}
{% block title %}{{ title }} | {{ block.super }}{% endblock title %}

{% block content %} {{ block.super }}
<div class="ui positive message">
  <div class="header">你已成功購買 </div>
  <p>恭喜你，你已成功購買以下商品</p>
</div>
<div class="ui segments">
  <div class="ui horizontal segments">
    <div class="ui center aligned segment">
      <p>訂單編號：{{ myorder.number }}</p>
    </div>
    <div class="ui center aligned segment">
      <p>買家：{{ myorder.shopper }}</p>
    </div>
    <div class="ui center aligned segment">
      <p>購買日期：{{ myorder.order_date }}</p>
    </div>
  </div>
  <div class="ui clearing segment">
    <div class="ui floated buttons">
      <a href="{% url 'member:shoppinglist' %}"><button class="ui green basic button">我的購物清單</button></a>
    </div>
  </div>
  <div class="ui segment">
    <table class="ui celled table" id='goodsTable'>
      <thead>
        <tr class="center aligned">
          <th>商品名稱/商品編號</th>
          <th>商品單價</th>
          <th>商品數量/商品總價</th>
          <th>運費</th>
          <th>結帳總金額</th>
          <th>訂單狀況</th>
        </tr>
      </thead>
      <tbody>
        {% for good in myorder.sold_goods.all %}
        <tr class="center aligned">
          <td class="left aligned">
            <a class="ui big image label">
              <img src="{{MEDIA_URL}}/{{ good.product.image }}"> {{ good.product }}
              <div class="detail">{{ good }}</div>
            </a>
          </td>
          <td class="middle aligned" id="{{ good.id }}" name="tdPrice">{{ good.price }}</td>
          <td class="middle aligned" name="tdQtySum">{{ myorder.order_notes_nonono }}</td>
          {% if forloop.first %}
          <td class="middle aligned" rowspan="{{myorder.sold_goods.all|length}}">${{ myorder.freight }}</td>
          <td class="middle aligned" rowspan="{{myorder.sold_goods.all|length}}">${{ myorder.total }}</td>
          <td class="middle aligned" rowspan="{{myorder.sold_goods.all|length}}">{{ myorder.get_status_display }}</td>
          {% endif %}
        </tr>
        {% endfor %}
        {% if myorder.notes %}
        <tr>
          <td colspan="7">
            <h3>買家的話：</h3>
            　　{{ myorder.notes }}
          </td>
        </tr>
        {% endif %}
      </tbody>
    </table>
  </div>
  <div class="ui segment">
    <div class="ui warning message">
      <div class="header"><i class="warning icon"></i> 您選擇使用7-11取貨付款服務，請注意以下取貨注意事項：
      </div><br/> ．到貨時，系統將發手機簡訊與email通知您取件時間。
      <br/> ．請務必於
      <span class="style2">7天內</span>至您所指定的門市取貨。<br/> ．若逾期未領，貨品將直接退還給賣家，您的帳號將累積一次未取貨次數。
      <br/> ．配送資料是定時與超商作資料交換，如遇通知卻取不到貨的情況，可利用
      <a href="https://eservice.7-11.com.tw/E-Tracking/search.aspx">超商系統</a>查詢。
    </div>
    <div class="ui info message">
      <i class="close icon"></i>
      <div class="header">賣家所提供的匯款帳戶：</div>
      <ol class="ui list">
        <li value=" * ">銀行名稱與代號：中國信託 (822)
          <ol>
            <li value=" - ">戶名：劉秋婕</li>
            <li value=" - ">銀行帳號：5325-4026-4159</li>
          </ol>
        </li>
        </br>
        <li value=" * ">銀行名稱與代號：郵局(700)
          <ol>
            <li value=" - ">戶名：劉秋婕</li>
            <li value=" - ">銀行帳號：0031005-1502435</li>
          </ol>
        </li>
      </ol>
    </div>
  </div>
</div>
{% endblock content %}

{% block js-foot %} {{ block.super }}
<script type="text/javascript">
  $(document).ready(function() {
    document.getElementsByClassName("step")[0].setAttribute("class", "step");
    document.getElementsByClassName("step")[1].setAttribute("class", "step");
    document.getElementsByClassName("step")[2].setAttribute("class", "active step");
    var j = "{{ myorder.order_notes }}";
    var j = j.replace(/&#39;/g, "'");
    var j = j.replace(/'/g, '"');
    var qppJson = jQuery.parseJSON(j);
    var priceNL = document.getElementsByName("tdPrice");
    var qtysumNL = document.getElementsByName("tdQtySum");
    for (i = 0; i < priceNL.length; i++) {
      for (j = 0; j < qppJson.length; j++) {
        if (qppJson[j].product_pk == priceNL[i].id) {
          qtysumNL[i].innerHTML = qppJson[j].quantity + " / $" + qppJson[j].price * qppJson[j].quantity
        }
      }
    }
  });
</script>
{% endblock js-foot %}

MMCB/checkout/templates/checkout/checkout-page.html
{% extends 'checkout/base.html' %}
{% block title %}{{ title }} | {{ block.super }}{% endblock title %}

{% block content %} {{ block.super }}
<table class="ui table">
  <thead>
    <tr>
      <th id='Image'>圖片</th>
      <th id='Description'>商品 - 規格</th>
      <th id='Quantity'>數量</th>
      <th id='Price'>金額</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.items %}
    <tr>
      <td class="one wide middle aligned">
        <div class="disabled ui image">
          <div class="floating ui grey circular label">{{ item.quantity }}</div>
          <img class="ui tiny rounded image" src="{{MEDIA_URL}}/{{ item.product.product.image }}">
        </div>
      </td>
      <td class="ten wide middle aligned">{{ item.product.product.name }}{{ item.product }}</td>
      <td class="zero wide middle aligned">{{ item.quantity }}</td>
      <td class="one wide middle aligned">$ {{ item.product.price }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<form class="ui form" method='POST' action='' id="myform">{% csrf_token %}
  <div class="ui hidden divider"></div>
  <div class="ui right aligned grid">
    <div class="left floated left aligned six wide column">
      <div class="ui small green message">
        <div class="header">小提醒：</div>
        <ul class="list">
          <li>若想修改預設全家店鋪號/寄送地址，請至會員中心修改。</li>
          <li>滿一千五免運費</li>
        </ul>
      </div>
      <div class="ui vertical fluid accordion menu">
        {% if not freight_only %}
        <div class="item">
          <a class="title"><i class="dropdown icon"></i>全家 貨到付款</a>
          <div class="content">
            <div class="grouped fields">
              <div class="item">
                <div class="header">您預設的全家店鋪號：</div>
                <div class="content">(於<a href="{% url 'member:info' %}">會員中心</a>新增/修改)</div>
              </div>
              {% for fmnumber in request.user.personalinfo.familynumber_set.all %}
              <div class="field" name="numberfield">
                <div class="ui radio checkbox">
                  <input type="radio" id="familynumber" name=delivery value={{fmnumber}}>
                  <label for="">{{ fmnumber }}</label>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        {% endif %}
        <div class="item">
          <a class="active title"><i class="dropdown icon"></i>大榮貨運</a>
          <div class="active content">
            <div class="grouped fields">
              <div class="item">
                <div class="header">您預設的寄送地址：</div>
                <div class="content">(於<a href="{% url 'member:info' %}">會員中心</a>新增/修改)</div>
              </div>
              {% for address in request.user.personalinfo.addresses_set.all %}
              <div class="field" name="addressfield">
                <div class="ui radio checkbox">
                  <input type="radio" id="address" name=delivery value={{address}}>
                  <label for="">{{ address }}</label>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="right floated left aligned ten wide column">
      <div class="field">
        <label for="comment">給買家的話（備註）:</label>
        <textarea class="form-control" rows="5" name="shopper_notes"></textarea>
      </div>
    </div>
  </div>
  <table class="ui very basic table">
    <thead>
      <tr>
        <th>
          <h3 class="ui header">總計</h3></th>
        <th class="right aligned">
          <div class="ui statistic">
            <div class="value" id="total">{% load humanize %} $ {{ cart.total|intcomma:False }}
            </div>
            <div class="label">TWD </div>
          </div>
        </th>
      </tr>
    </thead>
  </table>
  <div class="row">
    <a href="{% url 'cart:shopping-cart-show' %}"><button type='button' class="ui red basic huge button"> 返回購物車 </button></a>
    <button type='submit' class="ui right floated green basic huge button"><i class="checkmark icon"></i> 結帳確認 </button>
  </div>
  <div class="ui error message"></div>
</form>
<div class="ui pink message">
  </p>每週二，刷永豐信用卡單筆「滿1,000元送100元刷卡金」。單日限回饋100元，單平台限回饋300元，需登錄。了解更多。（活動期間：2016/7/1~9/30 ）*謹慎理財信用至上</p>
</div>
{% endblock content %}

{% block js-foot %} {{ block.super }}
<script type="text/javascript">
  $(document).ready(function() {
    document.getElementsByClassName("step")[0].setAttribute("class", "step");
    document.getElementsByClassName("step")[1].setAttribute("class", "active step");
    var all_cost = "{{ cost_total }}";
    $('.ui.radio.checkbox').checkbox({
      onChange: function() {
        var all_cost = "{{ cost_total }}";if (all_cost < 1500){
          if ($(this).attr('id') == 'familynumber') {
            all_cost = parseInt(all_cost) + 60;
            $("input[id='address']").attr("checked", false);
          } else if ($(this).attr('id') == 'address') {
            all_cost = parseInt(all_cost) + 90;
            $("input[id='familynumber']").attr("checked", false);
          } else {
            $("#total").text("ERROR!!");
            return false;
          }
        }else{
          return true;
        }
        $("#total").text("$ " + all_cost.toLocaleString());
      }
    });
    $('.ui.form')
      .form({
        fields: {
          delivery: {
            identifier: 'delivery',
            rules: [{
              type: 'checked',
              prompt: '請選擇您的運送方式'
            }]
          }
        }
      });
      $('.vertical.accordion').accordion({
        selector: {
          trigger: '.title '
        }
      });
  })
</script>
{% endblock js-foot %}