MMCB/MMCB/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from products import views

urlpatterns = [
    url(r'^$', views.store_list, name='store'),
    url(r'^cart/', include('shopping.urls', namespace='cart')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^member/', include('members.urls', namespace='member')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls', namespace='posts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 以下適用於網頁讀取"settings.py"中的 MEDIA_URL 與 MEDIA_ROOT 所用
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MMCB/posts/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from posts import views

urlpatterns = [
    url(r'^$', views.post_page, name='page'),
    url(r'^meta/$', views.meta, name='meta'),
    url(r'^products/', include([
        # READ(Retreive)
        url(r'^$', views.post_products_list, name='productlist'),
        # CREATE(Prodcut)
        url(r'^create/$', views.post_product_add, name='create'),

        # CREATE(Item)
        url(r'^add_item/$', views.post_item_add, name='add_item'),
        url(r'^add_item/(?P<good_id>\d+)/$', views.post_item_add, name='add_item'),

        # UPDATE
        url(r'^edit/(?P<good_id>\d+)/$', views.post_product_update, name='update'),

        # DELETE
        url(r'^delete/(?P<good_id>\d+)/$', views.post_product_delete, name='delete'),
    ])),
    url(r'^checkouts/', include([
        # READ(Retreive)
        url(r'^$', views.post_products_list, name='list'),
        # CREATE
        # UPDATE
        # DELETE
    ], namespace='checkouts')),
    url(r'^orders/', include([
        # READ(Retreive)
        url(r'^$', views.post_orders_list, name='orderlist'),
        url(r'^(?P<number>\d+)/$', views.posts_order, name='order'),
        # CREATE(Prodcut)
        # UPDATE
        url(r'^(?P<number>\d+)/(?P<do>.+)/(?P<fmnumber>\d+)/(?P<shiptime>.+)/$', views.posts_order_update, name='order_update'),
        # DELETE
    ])),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 以下適用於網頁讀取"settings.py"中的 MEDIA_URL 與 MEDIA_ROOT 所用
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MMCB/checkout/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _
from members.models import PersonalInfo
from products.models import Item
# 訂單編號、買家、連絡賣家、查看訂單
# 結帳時間
# 商品名稱/商品編號 (多個)
# 數量/商品總價
# 運費
# 結帳總金額
# 交易狀況（待付款，請轉帳至.../賣家確認金額中/已付款）
# 可執行動作 （通知已付款、(放棄此訂單/待賣家確認放棄/已放棄)）

# 訂單資訊:
# 賣出時間、商品名稱/編號、數量/商品總價、運費、總金額、付款方式/交易狀況、可執行動作（通知出貨）
# 會員帳號(ID)、姓名、手機、信箱、剩餘儲值金

# 買家交易明細:
# 付款資訊: 匯款銀行名、匯款銀行代碼、轉出帳號末五碼、匯款人姓名、匯款時間
# 收件人資料：收件人姓名、手機、收件地址

# 給賣家的話:

# 賣家出貨資訊:
# 出貨資料：出貨進度、預計出貨方式、預計出貨時間
# 給買家的話


class PurchaseOrder(models.Model):
    STATUS = {
        'Unpaid': 'UPD',
        'Paid': 'PAD',
        'ComfirmPayment': 'CFP',
        'Shipping': 'SPN',
        'Shipped': 'SPD',
        'Abandon': 'ABN',
        'CancelAbandonment': 'CCA',
        'ComfirmAbandonment': 'CFA',
        'Abandoned': 'ABD',
    }
    ORDER_STATUS = (
        (STATUS['Unpaid'], '待付款/匯款'),
        (STATUS['Paid'], '通知已付款'),
        (STATUS['ComfirmPayment'], '確認已付款'),
        (STATUS['Shipping'], '商品準備中'),
        (STATUS['Shipped'], '商品已寄出'),
        (STATUS['Abandon'], '放棄此訂單'),
        (STATUS['CancelAbandonment'], '取消放棄此訂單'),
        (STATUS['ComfirmAbandonment'], '待賣家確認放棄'),
        (STATUS['Abandoned'], '已放棄'),
    )
    METHOD = {
        'Family': 'FML',
        'KerryTJ': 'KTJ',
    }
    SHIP_METHOD = (
        (METHOD['Family'], '全家'),
        (METHOD['KerryTJ'], '大榮貨運'),
    )

    number = models.DecimalField(_('訂單編號'), max_digits=16, decimal_places=0,
                                 validators=[MinValueValidator(0)])
    buyer = models.ForeignKey(PersonalInfo, verbose_name=_('買家'))
    order_time = models.DateTimeField(_('訂購時間'), default=timezone.now)
    sold_goods = models.ManyToManyField(Item, verbose_name=_('已買商品'))
    freight = models.PositiveSmallIntegerField(_('運費'))
    ship_method = models.CharField(_('運送方式'), max_length=3, choices=SHIP_METHOD, default=METHOD['KerryTJ'])
    address = models.CharField(_('寄送地址'), max_length=64, default='')
    total = models.PositiveIntegerField(_('總額'))
    buyer_notes = models.TextField(_('備註'), default='')
    status = models.CharField(_('訂單狀態'), max_length=3, choices=ORDER_STATUS, default=STATUS['Unpaid'])
    order_notes = models.TextField(_('訂單清單'), default='')
    remittance_account = models.CharField(_('匯款帳號'), max_length=6, default="")
    remittance_time = models.DateTimeField(_('匯款日期時間'), blank=True, null=True)
    shipment_number = models.CharField(_('包裹貨件編號'), max_length=13, default="")
    shipment_time = models.DateTimeField(_('寄出日期時間'), blank=True, null=True)
    renounce_time = models.DateTimeField(_('放棄日期時間'), blank=True, null=True)

    class Meta:
        verbose_name = '購物清單'
        verbose_name_plural = '所有購物清單'
        ordering = ['-order_time']

    def get_sold_goods(self):
        return "\n".join([str(good) for good in self.sold_goods.all()])

MMCB/members/models.py
from django.db import models
from django.core import validators
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _
import allauth.app_settings


class PersonalInfo(models.Model):
    GENDER = (
        ('M', '男性'),
        ('F', '女性'),
    )
    user = models.OneToOneField(allauth.app_settings.USER_MODEL)
    name = models.CharField(_('姓名'), max_length=16)
    gender = models.CharField(_('性別'), max_length=1, choices=GENDER, default=GENDER[1][0])
    birthday = models.DateField(_('生日'), help_text=_('範例：1993/11/29'))
    phone = models.CharField(
        _('手機'), max_length=10, help_text=_('範例：0912456999'),
        validators=[validators.RegexValidator(
            r'^09\d{8}$', _('請輸入正確的手機號碼'), 'invalid')])
    email = models.EmailField()
    money = models.PositiveIntegerField(_('已消費金額'), default=0)

    class Meta:
        verbose_name = '會員資料'
        verbose_name_plural = '所有會員資料'
        ordering = ['-id']

    def __str__(self):
        return self.name


class Addresses(models.Model):
    personalinfo = models.ForeignKey('PersonalInfo', verbose_name=_('會員'))
    address = models.CharField(
        _('地址'), max_length=64, blank=True, default='',
    )

    class Meta:
        verbose_name = '地址'
        verbose_name_plural = '所有地址'

    def __str__(self):
        return self.address
    __repr__ = __str__


# alphanumeric = RegexValidator(r'^\d{5,6}$', '只能輸入5~6位數字') #Only alphanumeric characters are allowed.
class Accounts(models.Model):
    personalinfo = models.ForeignKey('PersonalInfo', verbose_name=_('會員'))
    account = models.CharField(
        _('匯款帳號(5碼)/無摺局號(6碼)'), max_length=6,
        blank=True, default='', validators=[RegexValidator(r'^\d{5,6}$', '請輸入5位帳號或6位局號！')],
    )

    class Meta:
        verbose_name = '匯款帳號/無摺局號'
        verbose_name_plural = '所有匯款帳號/無摺局號'

    def __str__(self):
        return self.account
    __repr__ = __str__


class FamilyNumber(models.Model):
    personalinfo = models.ForeignKey('PersonalInfo', verbose_name=_('會員'))
    number = models.CharField(
        _('全家店鋪號'), max_length=6,
        blank=True, default='', validators=[RegexValidator(r'^\d{6}$', '請輸入6位全家店鋪號！')],
    )

    class Meta:
        verbose_name = '全家店鋪號'
        verbose_name_plural = '所有全家店鋪號'

    def __str__(self):
        return self.number
    __repr__ = __str__

MMCB/products/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _


class Product(models.Model):
    name = models.CharField(_('商品名稱'), max_length=16)
    notes = models.TextField(_('商品描述'), blank=True, default='')
    onshelf_time = models.DateTimeField(_('上架時間'), default=timezone.now)
    image = models.ImageField(_('商品陳列圖片'), upload_to='ProductImages', null=True, blank=True)
    is_display = models.BooleanField(_('是否陳列商品'), default=True)
    freight_only = models.BooleanField(_('限制只能貨運'), default=False)

    def thumbnail(self):
        return mark_safe('<img src="/media/%s" width="30" height="30" />' % (self.image))
    thumbnail.short_description = 'Thumbnail'

    class Meta:
        verbose_name = '商品'
        verbose_name_plural = '所有商品'
        ordering = ['-onshelf_time', '-id']

    def __str__(self):
        return self.name
    __repr__ = __str__


class Images(models.Model):
    def get_image_filename(instance, filename):
        title = instance.product.name
        slug = slugify(title, allow_unicode=True)
        return "ProductImages/%s - %s" % (slug, filename)

    product = models.ForeignKey('Product', verbose_name=_('商品'))
    image = models.ImageField(upload_to=get_image_filename,
                              verbose_name=_('商品內容圖片'),
                              blank=True, null=True, )

    class Meta:
        verbose_name = '商品內容圖片'
        verbose_name_plural = '所有商品內容圖片'


class Item(models.Model):
    product = models.ForeignKey('Product', verbose_name=_('商品'))
    style = models.CharField(_('商品款式'), max_length=8)
    size = models.CharField(_('商品尺寸'), max_length=8)
    price = models.PositiveSmallIntegerField(_('商品價格'), default=0)
    pre_order = models.SmallIntegerField(_('預購量'), default=0)
    selling = models.PositiveSmallIntegerField(_('已出貨量'), default=0)
    selling_volume = models.PositiveSmallIntegerField(_('總出貨量'), default=0)
    reset_time = models.DateTimeField(_('上次歸零時間'), blank=True, null=True)
    is_reset = models.BooleanField(_('是否歸零'), default=False)
    is_shortage = models.BooleanField(_('是否缺貨'), default=False)

    class Meta:
        verbose_name = '商品項目'
        verbose_name_plural = '所有商品項目'

    def __str__(self):
        return "{} - {}".format(self.style, self.size)
    __repr__ = __str__

MMCB/posts/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from products.models import Product, Item, Images
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Button, Layout, Div, HTML, Fieldset, Field


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = [
            'name',
            'notes',
            'onshelf_time',
            'image',
            'is_display',
            'freight_only',
        ]
    def __init__(self, *args, submit_title=None, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div(
                Div('name', css_class="col-md-6"),
                Div('onshelf_time', css_class="col-md-2"),
                Div('is_display', css_class="col-md-2"),
                Div('freight_only', css_class="col-md-2"),
                css_class="row"
            ),
            Div(
                Div('notes', css_class="col-md-8"),
                Div(
                    Div(
                        HTML("""
                            {% if form.image.value %}
                            <img class="img-responsive" src="{{ MEDIA_URL }}{{ form.image.value }}">
                            {% endif %}
                        """, )
                    ),
                    Div('image'),
                    css_class="col-md-4"
                ),
                css_class='row'
            ),
            Div(
                Div(HTML("""

                <h4>商品內容圖片展示：</h4>
                <div class="ui tiny images">
                    {% for item in image_formset %}
                    {% if item.image.value %}
                    <img class="ui small image" src="{{ MEDIA_URL }}{{ item.image.value }}">
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="ui divider"></div>
                """, )),
            )
        )
        if submit_title:
            self.helper.add_input(Submit('submit', submit_title))
            self.helper.add_input(Button(
                'delete', '移除商品',
                css_class='btn btn-danger', onclick='javascript:ProductDelete();'))
            self.helper.add_input(Button(
                'delete', '歸零全選/全取消',
                css_class='btn', onclick='javascript:ResetAllItem();'))


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'product',
            'style',
            'size',
            'price',
            'pre_order',
            'selling',
            'selling_volume',
            'reset_time',
            'is_reset',
            'is_shortage',
        ]


BaseItemFormSet = inlineformset_factory(
    parent_model=Product, model=Item,
    fields=(
        'style',
        'size',
        'price',
        'pre_order',
        'selling',
        'selling_volume',
        'reset_time',
        'is_reset',
        'is_shortage',
    ), extra=0,
)


class ItemFormSet(BaseItemFormSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.template = 'bootstrap/table_inline_formset.html'
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.layout = Layout(
            Fieldset(
                Field('style', ),
                Field('size', ),
                Field('price', ),
                Field('pre_order', readonly=True),
                Field('selling', readonly=True),
                Field('selling_volume', readonly=True),
                Field('reset_time', readonly=True),
                Field('is_reset', ),
                Field('is_shortage', ),
            )
        )


class ImagesForm(forms.ModelForm):
    image = forms.ImageField(label='Images')

    class Meta:
        model = Images
        fields = [
            'image',
        ]

BaseImagesFormSet = inlineformset_factory(
    parent_model=Product, model=Images,
    fields=('image', ), extra=4, max_num=4,
)


class ImagesFormSet(BaseImagesFormSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.template = 'bootstrap3/table_inline_formset.html'
        self.helper.form_tag = False
        self.helper.disable_csrf = True

MMCB/base/views.py
from django.shortcuts import render

# Create your views here.

MMCB/posts/templates/posts/base.html
{% extends 'base.html' %}

{% block content %}{{ block.super }}
{% if errors %}
<div class="ui error message">
  <i class="close icon"></i>
  <div class="header">錯誤提醒</div>
  <ul class="list">
    {% for error in errors %}
    <li>{{ error }}</li>
    {% endfor %}
  </ul>
</div>
{% endif %}
{% endblock content%}

MMCB/posts/templates/posts/post_delete.html
{% extends 'posts/base.html' %}
  {% block title %}MMCB商品刪除 | {{ block.super }
{% endblock title %}

{% block content %}
  <h1> Delete </h1>
{% endblock content %}

MMCB/posts/templates/posts/post_list.html
{% extends 'posts/base.html' %}
{% block title %}
    {{ title }} | {{ block.super }}
{% endblock title %}

{% block content %}
  {{ block.super }}
  <div class="ui clearing segment">
      <h1 class="ui left floated header"> {{ title }} </h1>
      <a href="{% url 'posts:add_detail' %}"><button class="ui inverted right floated green button"><i class="add square icon"></i>新增內容</button></a>
      <a href="{% url 'posts:create' %}"><button class="ui inverted right floated red button"><i class="plus icon"></i> 新增商品</button></a>
      <h4 class="ui horizontal divider header"><i class="gift icon"></i> Product List </h4>
      <div class="ui massive selection animated list">
          {% for obj in object_list %}
          <div class="item">
              <img class="ui avatar image" src="{{MEDIA_URL}}/{{ obj.image }}">
              <div class="middle aligned content">
                  <a class="header" href={% url 'posts:update' id=obj.id %}>{{ obj.name }}
                    【P{{ obj.id }}-{% with obj.details.all|length as count %}C{{count}}{% endwith %}】</a>
                  <small>{{obj.date}}</small>
              </div>
              <div class="right floated content">
                  {% if obj.is_display %}
                  <i class="checkmark icon"></i> {% else %}
                  <i class="remove icon"></i> {% endif %}
              </div>
          </div>
          {% endfor %}
      </div>
  </div>
{% endblock content %}

MMCB/posts/templates/posts/post_order.html
{% extends 'posts/base.html' %}
{% block title %} {{ title }} | {{ block.super }} {% endblock title %}

{% block content %} {{ block.super }}
<div class="ui segment">
  <div class="ui right aligned grid">
    <div class="left floated left aligned four wide column">
      <a href="{% url 'posts:orderlist' %}"><button class="ui green basic button">返回訂單列表</button></a>
    </div>
    <div class="four wide column">
      <div class="input-group date" id='datetimepicker'>
        <input type="text" class="form-control" id="datetime" placeholder="包裹寄件日期/時間" />
          <div class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </div>
      </div>
    </div>
    <div class="four wide column">
      <div class="ui form">
        <div class="field">
          <input type="text" name="shipping[number]" placeholder="貨物包裹編號" maxlength="13">
        </div>
      </div>
    </div>
    <div class="right floated right aligned four wide column">
      <div class="ui selection dropdown">
        <input type="hidden" name="status">
        <i class="dropdown icon"></i>
        <div class="default text">更改 訂單狀況</div>
        <div class="menu">
          {% for key, value in all_status %}
          <div class="item" data-value="{{ key }}">{{ value }}</div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

<div class="ui segments" id="printableArea">
  <div class="floating ui blue label" onclick="printDiv('printableArea')"><i class="print icon"></i>Print</div>
  <div class="ui horizontal segments">
    <div class="ui center aligned five wide segment">
      <p>訂單編號：{{ myorder.number }}</p>
    </div>
    <div class="ui center aligned five wide segment">
      <p>買家：{{ myorder.buyer }}</p>
    </div>
    <div class="ui center aligned five wide segment">
      <p>購買日期：{{ myorder.order_time }}</p>
    </div>
  </div>
  <div class="ui segment">
    <table class="ui compact table" id='goodsTable'>
      <thead>
        <tr class="center aligned">
          <th>商品名稱/商品編號</th>
          <th>商品單價</th>
          <th>商品數量/商品總價</th>
          <th>運送方式/費用</th>
          <th>結帳總金額</th>
          <th>訂單狀況</th>
        </tr>
      </thead>
      <tbody>
        {% for good in myorder.sold_goods.all %}
        <tr class="center aligned">
          <td class="left aligned">　{{ good.product }} - {{ good }}</td>
          <td class="middle aligned" id="{{ good.id }}" name="tdPrice">{{ good.price }}</td>
          <td class="middle aligned" name="tdQtySum">{{ myorder.order_notes_nonono }}</td>
          {% if forloop.first %}
          <td class="middle aligned" rowspan="{{myorder.sold_goods.all|length}}"><p>{{ myorder.get_ship_method_display }}</p>${{ myorder.freight }}</td>
          <td class="middle aligned" rowspan="{{myorder.sold_goods.all|length}}">${{ myorder.total }}</td>
          <td class="middle aligned" rowspan="{{myorder.sold_goods.all|length}}">{{ myorder.get_status_display }}</td>
          {% endif %}
        </tr>
        {% endfor %}
        {% if myorder.notes %}
        <tr>
          <td colspan="7">
            <h3>買家的話：</h3>
            　　{{ myorder.notes }}
          </td>
        </tr>
        {% endif %}
      </tbody>
    </table>
  </div>
  <div class="ui segment">
    <div class="ui equal width grid">
      <div class="column">
        <table class="ui compact table">
          <thead>
            <tr>
              <th colspan=3>買家資料</th>
            </tr>
          </thead>
          <tbody class="center aligned">
            <tr>
              <td class="five wide">姓名</td>
              <td colspan=2 class="left aligned">{{ buyer.name }}</td>
            </tr>
            <tr>
              <td>性別</td>
              <td colspan=2 class="left aligned">{{ buyer.get_gender_display }}</td>
            </tr>
            <tr>
              <td>生日</td>
              <td colspan=2 class="left aligned">{{ buyer.birthday }}</td>
            </tr>
            <tr>
              <td>手機</td>
              <td colspan=2 class="left aligned">{{ buyer.phone }}</td>
            </tr>
            <tr>
              <td>信箱</td>
              <td colspan=2 class="left aligned">{{ buyer.email }}</td>
            </tr>
            <tr>
              <td>地址1</td>
              <td colspan=2 class="left aligned">{{ buyer.addresses_set.all.0 }}</td>
            </tr>
            <tr>
              <td>地址2</td>
              <td colspan=2 class="left aligned">{{ buyer.addresses_set.all.1 }}</td>
            </tr>
            <tr>
              <td>匯款/無摺</td>
              <td class="left aligned">{{ buyer.accounts_set.all.0 }}</td>
              <td class="left aligned">{{ buyer.accounts_set.all.1 }}</td>
            </tr>
            <tr>
              <td>FM店鋪號</td>
              <td class="left aligned">{{ buyer.familynumber_set.all.0 }}</td>
              <td class="left aligned">{{ buyer.familynumber_set.all.1 }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="column">
        <table class="ui compact table">
          <thead>
            <tr>
              <th colspan="2">訂單內容資訊</th>
            </tr>
          </thead>
          <tbody class="center aligned warning">
            <tr class="positive">
              <td>買家選擇地址</td>
              <td>{{ myorder.address }}</td>
            </tr>
            <tr>
              <td class="five wide">買家匯款時間</td>
              <td>{%if myorder.remittance_time != None%}{{ myorder.remittance_time }}{% else %}尚未匯款{%endif%}</td>
            </tr>
            <tr>
              <td>買家匯款帳號</td>
              <td>{%if myorder.remittance_account%}{{ myorder.remittance_account }}{%else%}尚無帳號{%endif%}</td>
            </tr>
            <tr class="warning">
              <td>包裹寄出時間</td>
              <td>{%if myorder.shipment_time != None%}{{ myorder.shipment_time }}{% else %}尚未寄出{%endif%}</td>
            </tr>
            <tr class="warning">
              <td>包裹貨件編號</td>
              <td>{%if myorder.shipment_number%}{{ myorder.shipment_number }}{%else%}尚無編號{%endif%}</td>
            </tr>
            <tr>
              <td>買家備註</td>
              <td class="left aligned">　　{{ myorder.buyer_notes }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>
</div>
{% endblock content %}

{% block js-foot %} {{ block.super }}
<script type="text/javascript">
$(function() {
    $('#datetimepicker').datetimepicker({
      format: 'YYYY-MM-DD HH:mm',
      useCurrent: false, //Important! See issue #1075
    });
  });

  function printDiv(divName) {
     var printContents = document.getElementById(divName).innerHTML;
     var originalContents = document.body.innerHTML;
     document.body.innerHTML = printContents;
     window.print();
     document.body.innerHTML = originalContents;
  }

  $(document).ready(function() {
    var j = "{{ myorder.order_notes }}";
    var j = j.replace(/&#39;/g, "'");
    var j = j.replace(/'/g, '"');
    var qppJson = jQuery.parseJSON(j);
    var priceNL = document.getElementsByName("tdPrice");
    var qtysumNL = document.getElementsByName("tdQtySum");
    for (i = 0; i < priceNL.length; i++) {
      for (j = 0; j < qppJson.length; j++) {
        if (qppJson[j].product_pk == priceNL[i].id) {
          qtysumNL[i].innerHTML = qppJson[j].quantity + " / $" + qppJson[j].price * qppJson[j].quantity
        }
      }
    }

    $('.ui.dropdown').dropdown({
      onChange: function(key, value) {
        if (confirm('您確定要把訂單狀態更改為「motion」嗎？'.replace('motion', value))) { //.replace('motion', display)
          console.log(key)
          console.log(value)
          if (key=='SPD' && value == '商品已寄出'){
            var dt = $('#datetime').val();
            var fmnumber = $("input[name='shipping[number]']").val();
            if (dt == '' || fmnumber == '') {
              alert('請記得選擇您的「包裹寄件日期與時間」和「包裹編號」再點選"商品已寄出"，謝謝。');
              return false;
            }
            var url = "{% url 'posts:order_update' number=myorder.number do=999 fmnumber=888 shiptime=777 %}"
            var url = url.replace('999', key).replace('888', fmnumber).replace('777', dt);
            window.location.href = url
          }
          else{
            window.location.href = "{% url 'posts:order_update' number=myorder.number do='999' shiptime='888' fmnumber='777' %}".replace('999', key);
          }
        } else {
          // Do nothing!
        }
      }
    });
  });
</script>
{% endblock js-foot %}

MMCB/posts/templates/posts/post_products_list.html
{% extends 'posts/base.html' %}
{% block title %} {{ title }} | {{ block.super }} {% endblock title %}

{% block content %}
<div class="ui clearing segment">
  <h1 class="ui left floated header"> {{ title }} / </h1>
  <a href="{% url 'posts:orderlist' %}"><button class="ui basic teal large button">訂單管理頁面</button></a>
  <a href="{% url 'posts:add_item' %}"><button class="ui right floated green basic button"><i class="add square icon"></i>新增內容</button></a>
  <a href="{% url 'posts:create' %}"><button class="ui right floated red basic button"><i class="plus icon"></i> 新增商品</button></a>
  <form method="get" class="ui form">
    <div class="field">
      <div class="ui category search">
        <div class="ui icon input">
          <input class="prompt" type="text" name='search_name' placeholder="搜尋 商品名稱">
          <i class="search icon"></i>
        </div>
      </div>
    </div>
    <div class="ui right floated ui buttons">
      <button type="submit" class="ui blue basic button">搜尋</button>
      <div class="or"></div>
      <a href="{% url 'posts:productlist' %}"><button type="button" class="ui red basic button">取消</button></a>
    </div>
  </form>
  <h4 class="ui horizontal divider header"><i class="gift icon"></i> Product List </h4>
  <div class="ui massive selection animated list">
    {% for good in all_products %}
    <div class="item">
      <img class="ui avatar image" src="{{MEDIA_URL}}/{{ good.image }}">
      <div class="middle aligned content">
        <a class="header" href="{% url 'posts:update' good_id=good.id %}">{{ good.name }}
                    【{% with good.item_set.all|length as count %}{{count}}項內容{% endwith %}】</a>
        <small>{{good.date}}</small>
      </div>
      <div class="right floated content">
        {% if good.freight_only %}<i class="shipping icon"></i>{% endif %}
        {% if good.is_display %}
        <i class="checkmark icon"></i> {% else %}
        <i class="remove icon"></i> {% endif %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}